add_newline = true

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[package]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"

[aws]
format = ' [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"

[aws.region_aliases]
ap-southeast-1 = "apac_1"
ap-southeast-2 = "apac_2"
us-east-1 = "us_e1"
us-west-2 = "us_w2"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false